# Changes here will be overwritten by Copier
_commit: 0.0.13
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar-Ramírez
author_username: edgarrmondragon
python_main_version: '3.10'
repository_name: tap-pomelo
repository_namespace: edgarrmondragon
repository_provider: github.com
tap_auth_method: OAuth2
tap_id: tap-pomelo
tap_package_command_line_name: tap-pomelo
tap_package_distribution_name: tap-pomelo
tap_package_import_name: tap_pomelo
tap_source_description: Tecnología para lanzar y escalar servicios financieros en
    América Latina
tap_source_id: Pomelo
tap_source_name: Pomelo
tap_stream_type: REST
vscode_files: true
