[tool.poetry]
name = "tap-pomelo"
version = "0.0.1"
description = "`tap-pomelo` is a Singer tap for Pomelo, built with the Meltano SDK for Singer Taps."
authors = ["Edgar-Ramírez <edgarrm358@gmail.com>"]
keywords = [
  "ELT",
  "singer.io",
  "Pomelo",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-pomelo"
repository = "https://github.com/edgarrmondragon/tap-pomelo"
documentation = "https://github.com/edgarrmondragon/tap-pomelo#readme"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = "0.23.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
use_parentheses = true
include_trailing_comma = true
src_paths = "tap_pomelo"
known_first_party = "tap_pomelo"
add_imports = [
  "from __future__ import annotations",
]

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = ["backoff.*"]

[build-system]
requires = ["poetry-core>=1,<2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
"tap-pomelo" = "tap_pomelo.tap:TapPomelo.cli"

[tool.ruff]
ignore = [
  "ANN101", # missing-type-self
  "DJ", # flake8-django
]
line-length = 88
select = ["ALL"]
src = ["tap_pomelo", "tests"]
target-version = "py37"

[tool.ruff.per-file-ignores]
"noxfile.py" = ["ANN"]
"tests/*" = [
  "ANN201", # missing-return-type-public-function
  "S101", # assert
  "SLF001", # private-member-access
]

[tool.ruff.isort]
known-first-party = ["tap_pomelo"]

[tool.ruff.pydocstyle]
convention = "google"
