[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core<2,>=1",
]

[tool.poetry]
name = "tap-pomelo"
version = "0.0.1"
description = "`tap-pomelo` is a Singer tap for Pomelo, built with the Meltano SDK for Singer Taps."
authors = [ "Edgar-Ramírez <edgarrm358@gmail.com>" ]
maintainers = [ "Edgar-Ramírez <edgarrm358@gmail.com>" ]
classifiers = [
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
keywords = [
  "ELT",
  "singer.io",
  "Pomelo",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/edgarrmondragon/tap-pomelo"
repository = "https://github.com/edgarrmondragon/tap-pomelo"
documentation = "https://github.com/edgarrmondragon/tap-pomelo#readme"
scripts."tap-pomelo" = "tap_pomelo.tap:TapPomelo.cli"

[tool.poetry.dependencies]
python = ">=3.8"
singer-sdk = "~=0.41.0"

[tool.poetry.dev-dependencies]
singer-sdk = { version = "*", extras = [ "testing" ] }

[tool.ruff]
target-version = "py38"

line-length = 88
lint.select = [
  "ALL",
]
lint.ignore = [
  "ANN101", # missing-type-self
  "DJ",     # flake8-django
]
lint.per-file-ignores."noxfile.py" = [
  "ANN",
]
lint.per-file-ignores."tests/*" = [
  "ANN201", # missing-return-type-public-function
  "S101",   # assert
  "SLF001", # private-member-access
]
lint.isort.known-first-party = [ "tap_pomelo" ]
lint.isort.required-imports = [
  "from __future__ import annotations",
]
lint.pydocstyle.convention = "google"

[tool.pyproject-fmt]
max_supported_python = "3.13"

[tool.pytest.ini_options]
addopts = "-vvv"

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [ "backoff.*" ]
