name: Build and publish

permissions:
  contents: read

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build wheel and sdist
    runs-on: ubuntu-24.04
    outputs:
      name: ${{ steps.baipp.outputs.package_name }}
      version: ${{ steps.baipp.outputs.package_version }}
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: hynek/build-and-inspect-python-package@efb823f52190ad02594531168b7a2d5790e66516 # v2.14.0
      id: baipp

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-24.04
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/${{ needs.build.outputs.name }}/${{ needs.build.outputs.version }}
    permissions:
      contents: write # Upload artifacts to release
      id-token: write # Required by pypa/gh-action-pypi-publish for trusted publishing

    steps:
    - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: Packages
        path: dist
    - uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
